# Generated by Django 3.0.4 on 2020-04-12 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readitcomments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readittags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='slug')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('url', models.URLField(null=True)),
                ('author', models.ForeignKey(blank=True, default=1, editable=False, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category_author', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_parent', to='blog.Category', verbose_name='category_parent')),
            ],
            options={
                'verbose_name': 'verbose_category_name',
                'verbose_name_plural': 'verbose_category_name_plural',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='slug')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='short_description')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='post_image')),
                ('url', models.URLField(null=True)),
                ('author', models.ForeignKey(blank=True, default=1, editable=False, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='post_author', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_category', to='blog.Category', verbose_name='category')),
                ('comments', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='readitcomments.Comment')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='post_tags', to='readittags.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'verbose_post_name',
                'verbose_name_plural': 'verbose_post_name_plural',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPost',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.CharField(db_index=True, max_length=200, verbose_name='slug')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='updated')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='short_description')),
                ('image', models.TextField(max_length=100, null=True, verbose_name='post_image')),
                ('url', models.URLField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, default=1, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blog.Category', verbose_name='category')),
                ('comments', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='readitcomments.Comment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical verbose_post_name',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.CharField(db_index=True, max_length=200, verbose_name='slug')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='updated')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('url', models.URLField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, default=1, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blog.Category', verbose_name='category_parent')),
            ],
            options={
                'verbose_name': 'historical verbose_category_name',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
