# Generated by Django 3.0.4 on 2020-04-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readitcomments', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='comments',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='readitcomments.Comment'),
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='post_image'),
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='readitcomments.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='post_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='short_description'),
        ),
    ]
