# Generated by Django 3.0.4 on 2020-05-23 07:40

import blog.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='post_image'),
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='short_description',
            field=models.TextField(blank=True, default='', verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='post_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=blog.fields.ImagesField(blank=True, null=True, upload_to='images/post/thumbnail/', verbose_name='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True, default='', verbose_name='short_description'),
        ),
    ]
