# Generated by Django 3.0.4 on 2020-05-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200523_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
    ]
