# Generated by Django 3.0.4 on 2020-05-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200526_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='optimized_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='post_image'),
        ),
        migrations.AddField(
            model_name='historicalpost',
            name='thumbnail_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='post_image'),
        ),
        migrations.AddField(
            model_name='post',
            name='optimized_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post/optimized', verbose_name='post_image'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post/thumbnail', verbose_name='post_image'),
        ),
    ]
