# Generated by Django 3.0.4 on 2020-04-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200417_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
