# Generated by Django 3.0.4 on 2020-06-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200526_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='historicalpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalpost',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCategory',
        ),
        migrations.DeleteModel(
            name='HistoricalPost',
        ),
    ]
