# Generated by Django 3.0.4 on 2020-06-25 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20200625_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPost',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.CharField(db_index=True, max_length=200, verbose_name='slug')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='updated')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('url', models.URLField(null=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('short_description', models.TextField(blank=True, default='', verbose_name='short_description')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='post_image')),
                ('optimized_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='post_image')),
                ('thumbnail_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='post_image')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, default=1, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blog.Category', verbose_name='category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical verbose_post_name',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.CharField(db_index=True, max_length=200, verbose_name='slug')),
                ('updated', models.DateTimeField(blank=True, editable=False, verbose_name='updated')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='created')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('url', models.URLField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, default=1, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blog.Category', verbose_name='category_parent')),
            ],
            options={
                'verbose_name': 'historical verbose_category_name',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
