# Generated by Django 3.0.4 on 2020-05-12 13:22

import blog.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200417_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='images',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='post_image'),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=blog.fields.BlogImageField(blank=True, null=True, upload_to='imagess/', verbose_name='post_image'),
        ),
    ]
