# Generated by Django 3.0.4 on 2020-05-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200512_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='post_image')),
                ('recent_post_thumb', models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='post_image')),
                ('category_thumb', models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='post_image')),
                ('article_thumb', models.ImageField(blank=True, null=True, upload_to='images/post/', verbose_name='post_image')),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalpost',
            name='images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='image',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='blog.PostImage', verbose_name='post_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.PostImage', verbose_name='post_images'),
        ),
    ]
