version: '3'

services:
  nginx:
    image: nginx
    ports:
      - '5000:80'
      - '443:443'
    links:
      - webapp
    volumes:
      - readit_sock:/sock/
      - readit_media:/usr/src/media/
      - readit_static:/usr/src/static/
      - ./config/nginx.conf:/etc/nginx/nginx.conf
  webapp:
    build: docker/webapp
    env_file: .env
    volumes:
      - readit_sock:/sock/
      - readit_static:/usr/src/webapp/static/
      - readit_media:/usr/src/webapp/media/
      - ./webapp/:/usr/src/webapp/
      - ./config/:/usr/src/config/
#    links:
#      - memcached
#      - postgres
    command: uwsgi --ini /usr/src/config/uwsgi.ini
#  postgres:
#    image: postgres
#    env_file: .env
#    volumes:
#      - readit_postgres:/var/lib/postgresql/data
#      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
#    command: -c 'config_file=/etc/postgresql/postgresql.conf'
#  memcached:
#    image: memcached
#    command: -m 512
#  rabbitmq:
#    image: rabbitmq
#    env_file: .env
#    ports:
#      - '5672:5672'
#    volumes:
#      - readit_rabbitmq:/var/lib/rabbitmq

volumes:
  readit_sock:
  readit_static:
  readit_media:
#  readit_postgres:
#  readit_rabbitmq:
