# Generated by Django 3.0.4 on 2020-04-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readitcomments', '0004_auto_20200416_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
