# Generated by Django 3.0.4 on 2020-04-17 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readitcomments', '0006_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
