# Generated by Django 3.0.4 on 2020-05-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readitcomments', '0008_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
